
export  const convertDBToDataType: { [key: string]: 'string' | 'number' | 'boolean' | 'date' | 'datetime' } = {
    bigint: 'number',
    binary: 'string',
    bit: 'boolean',
    char: 'string',
    date: 'date',
    datetime: 'date',
    datetime2: 'date',
    decimal: 'number',
    float: 'number',
    hierarchyid: 'number',
    image: 'string',
    int: 'number',
    money: 'number',
    nchar: 'string',
    ntext: 'string',
    numeric: 'number',
    nvarchar: 'string',
    real: 'number',
    smalldatetime: 'date',
    smallint: 'number',
    smallmoney: 'number',
    text: 'string',
    time: 'datetime',
    timestamp: 'datetime',
    tinyint: 'number',
    uniqueidentifier: 'number',
    varbinary: 'string',
    varchar: 'string',
    xml: 'string',
}