import { typeScriptDataType } from "../SvamSPIntellisense/SvamSPIntellisense";

export const convertDBtoTypeScriptType: { [key: string]: typeScriptDataType } = {
    bigint: 'number',
    binary: 'string',
    bit: 'boolean',
    char: 'string',
    date: 'Date',
    datetime: 'Date',
    datetime2: 'Date',
    decimal: 'number',
    float: 'number',
    hierarchyid: 'number',
    image: 'any',
    int: 'number',
    money: 'number',
    nchar: 'string',
    ntext: 'string',
    numeric: 'number',
    nvarchar: 'string',
    real: 'number',
    smalldatetime: 'Date',
    smallint: 'number',
    smallmoney: 'number',
    text: 'string',
    time: 'Date',
    timestamp: 'Date',
    tinyint: 'number',
    uniqueidentifier: 'number',
    varbinary: 'string',
    varchar: 'string',
    xml: 'any',
}