export interface ITableMeta {
    tablename: string;
    columnname: string,
    is_nullable: boolean,
    datatype: string,
    referencedtablename?: string,
    referencedcolumnname?: string,
    parentcolumnname?: string,

    max_length: number

    isprimarykey: boolean

    isautogenerated: boolean
}